In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding
from tensorflow.compat.v1.losses import sparse_softmax_cross_entropy


In [3]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
one_hot("amazing restaurant",30)

[22, 3]

In [6]:
vocab_size=30

encoded_reviews=[one_hot(d,vocab_size)for d in reviews]
encoded_reviews

[[29, 2],
 [22, 3],
 [26, 15],
 [13, 18, 29],
 [16, 4, 8],
 [26, 2],
 [28, 4, 24],
 [27, 28],
 [27, 20],
 [14, 29]]

In [7]:
max_length=3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[29,  2,  0],
       [22,  3,  0],
       [26, 15,  0],
       [13, 18, 29],
       [16,  4,  8],
       [26,  2,  0],
       [28,  4, 24],
       [27, 28,  0],
       [27, 20,  0],
       [14, 29,  0]])

In [8]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [9]:

X = padded_reviews
y = sentiment

In [10]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              150       
                                                                 
 flatten (Flatten)           (None, 15)                0         
                                                                 
 dense (Dense)               (None, 1)                 16        
                                                                 
Total params: 166 (664.00 Byte)
Trainable params: 166 (664.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [11]:
model.fit(X, y, epochs=50, verbose=0)

In [12]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 190ms/step - loss: 0.6407 - accuracy: 1.0000


1.0

In [14]:
weights = model.get_layer('embedding').get_weights()[0]
weights

array([[-4.89718169e-02, -9.65712517e-02, -7.01138675e-02,
        -1.44302621e-02, -2.75799707e-02],
       [ 1.89033039e-02,  2.68577449e-02,  3.02799009e-02,
        -3.06964163e-02, -2.97040474e-02],
       [ 1.48057714e-02,  4.91793454e-03, -5.01881838e-02,
        -9.19120573e-03,  4.76659611e-02],
       [ 9.41013619e-02, -9.75510776e-02, -8.70364457e-02,
        -4.31768298e-02,  1.00290338e-02],
       [-1.38426339e-02, -1.57074593e-02,  3.07228472e-02,
        -4.72305622e-03, -2.27493118e-03],
       [-2.94780377e-02,  2.16229074e-02, -3.77551205e-02,
         2.12617181e-02,  4.25846688e-02],
       [-4.58459370e-02,  9.60461050e-03,  3.82972620e-02,
         4.73576300e-02, -4.06580940e-02],
       [ 6.89436123e-03, -2.21824404e-02, -3.57169621e-02,
        -3.75881791e-05,  2.00402476e-02],
       [ 3.90158072e-02,  8.15224275e-03,  8.73327255e-03,
         9.15926602e-03,  9.62204784e-02],
       [-4.09375504e-03, -2.04125792e-03,  4.89750616e-02,
        -2.73854136e-02

In [15]:
len(weights)

30

In [16]:
weights[11]

array([ 0.00900775,  0.04136845, -0.03065546, -0.04925803, -0.02222034],
      dtype=float32)

In [17]:
weights[3]

array([ 0.09410136, -0.09755108, -0.08703645, -0.04317683,  0.01002903],
      dtype=float32)